package com.thor.core.common.profile

import android.content.Context
import java.io.File

/**
 * Where a profile's belongings live on disk.
 *
 * Everything a profile owns sits under one directory named after its id, so
 * deleting a profile is deleting a directory, and a profile cannot leave
 * fragments behind in four different places. Ids are validated as inert (see
 * `LauncherProfile.isValidId`) precisely because they become path segments.
 */
object ProfileFiles {

    private const val ROOT = "profiles"
    private const val SETTINGS = "settings.json"
    private const val DATABASE = "library.db"
    private const val SCREENSHOTS = "screenshots"
    const val AVATAR_PREFIX = "avatar"

    fun root(context: Context): File = File(context.filesDir, ROOT)

    fun directory(context: Context, profileId: String): File =
        File(root(context), profileId).apply { mkdirs() }

    fun settings(context: Context, profileId: String): File =
        File(directory(context, profileId), SETTINGS)

    /**
     * Where a game's screenshots live, one directory per entry.
     *
     * Inside the profile directory rather than in shared storage, and that is the
     * whole reason it is here: [com.thor.data.backup.BackupManager] zips this
     * directory whole, so screenshots are backed up, restored and carried between
     * devices without a single line being written for them. Putting them in
     * `Pictures/` would have been more discoverable and would have quietly left
     * them out of every backup.
     *
     * A directory per entry rather than one flat folder with the id in the file
     * name, so counting and deleting a game's shots is a directory listing rather
     * than a scan of everything ever captured.
     */
    fun screenshots(context: Context, profileId: String, entryId: String): File =
        File(File(directory(context, profileId), SCREENSHOTS), entryId.sanitizedForPath())

    /** The root of every entry's shots, for sweeps and counts. */
    fun screenshotRoot(context: Context, profileId: String): File =
        File(directory(context, profileId), SCREENSHOTS)

    /**
     * An entry id made safe to be a directory name.
     *
     * Ids are generated by the launcher and are usually inert, but not always: a
     * platform folder's id is `folder:platform:nes`, and a colon is not legal in a
     * path on every filesystem this could be restored onto. Replaced rather than
     * rejected, because the id has to keep working as a key.
     */
    private fun String.sanitizedForPath(): String =
        map { if (it.isLetterOrDigit() || it == '-' || it == '_') it else '_' }.joinToString("")

    /**
     * Room owns three files per database — the database, its write-ahead log and
     * its shared-memory index — and creates the latter two beside the first, so
     * only the primary path is named here.
     */
    fun database(context: Context, profileId: String): File =
        File(directory(context, profileId), DATABASE)

    fun avatar(context: Context, profileId: String, fileName: String): File =
        File(directory(context, profileId), fileName)

    /**
     * Profile directories already on disk, newest first.
     *
     * Deliberately does not create anything — unlike [directory], which mkdirs
     * as a side effect. This is asked *before* a profile exists, to find out
     * whether one already does.
     */
    fun existingIds(context: Context): List<String> =
        root(context).listFiles().orEmpty()
            .filter(File::isDirectory)
            .sortedByDescending(File::lastModified)
            .map(File::getName)

    /**
     * How much a directory looks like somebody's actual profile.
     *
     * Not a byte count, a ranking. A settings file outranks any database,
     * because it exists only once something has been configured — where Room
     * creates a database the instant it is opened, so a profile nobody ever used
     * still has one, and going by mere existence would rate an empty directory
     * as highly as a full one. Below that, the larger library wins.
     *
     * Zero means nothing worth recovering.
     */
    fun dataWeight(context: Context, profileId: String): Long {
        val directory = File(root(context), profileId)
        val settings = if (File(directory, SETTINGS).exists()) SETTINGS_WEIGHT else 0L
        return settings + File(directory, DATABASE).length()
    }

    /** Dominates any plausible database size, so settings always win the ranking. */
    private const val SETTINGS_WEIGHT = 1L shl 40

    /** Removes a profile's entire directory. Safe to call for an unknown id. */
    fun delete(context: Context, profileId: String): Boolean =
        File(root(context), profileId).deleteRecursively()
}
